sudo: false
language: node_js
node_js:
  - 4
  - 6
  - 8

# Make sure we have new NPM.
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g npm
  - npm config set loglevel warn

script:
  - npm run lint
  - npm run test
